# .github/workflows/lint.yml
name: Lint and Type Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run Black (code formatter)
        run: black --check --diff .

      - name: Run Ruff (linter & auto fixer)
        run: ruff check .

      - name: Run isort (import sorter)
        run: isort --check-only --diff .

      - name: Run mypy (type checker)
        run: mypy backend/ --ignore-missing-imports
